version: '2'

services:
  taskmanager_backend:
    image: 'taskmanager_backend'
    container_name: taskmanager_backend
    depends_on:
      - taskmanager_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskmanager_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    expose:
      - "8081"
  taskmanager_frontend:
    image: 'taskmanager_frontend'
    container_name: taskmanager_frontend
    ports:
      - "8080:8080"
    expose:
      - "8080"
  taskmanager_db:
    image: 'taskmanager_postgres'
    container_name: taskmanager_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres